program LantuSale;

{%ToDo 'LantuSale.todo'}

uses
  Forms,
  Windows,
  SysUtils,
  Graphics,
  Controls,
  DataM in 'DataM.pas' {DataMForm: TDataModule},
  Splash in 'Splash.pas' {SplashForm},
  SysPublic in 'SysPublic.pas',
  FillInComBoBox in 'FillInComBoBox.pas',
  SysPublicTmp in 'SysPublicTmp.pas',
  ShowPicture in 'ShowPicture.pas' {ShowPictureForm},
  Base in 'Base.pas' {BaseForm},
  DiskSerialNumber in 'DiskSerialNumber.pas',
  BaseEx in 'BaseEx.pas' {BaseExForm},
  BaseExDrag in 'BaseExDrag.pas' {BaseExDragForm},
  SetFormStyle in 'SetFormStyle.pas' {SetFormStyleForm},
  PageCount in 'PageCount.pas' {PageCountForm},
  SetComboBox in 'SetComboBox.pas',
  ProgressBar in 'ProgressBar.pas' {ProgressBarForm},
  ShowProgress in 'ShowProgress.pas',
  DragMoveComponent in 'DragMoveComponent.pas' {DragMoveComponentForm},
  Find in 'Find.pas' {FindForm},
  DBTreeView in 'DBTreeView.pas' {DBTreeViewForm},
  BaseNormal in 'BaseNormal.pas' {BaseNormalForm},
  UserLimit in 'UserLimit.pas' {UserLimitForm},
  MyInfo in 'MyInfo.pas' {MyInfoForm},
  SoftDataType in 'SoftDataType.pas',
  TestMain in 'TestMain.pas' {TestMainForm},
  CheckPrint in 'CheckPrint.pas' {CheckPrintForm},
  FindPublic in 'FindPublic.pas' {FindPublicForm},
  FilterPublic in 'FilterPublic.pas' {FilterPublicForm},
  BaseInfo in 'BaseInfo.pas' {BaseInfoForm},
  BaseEdit in 'BaseEdit.pas' {BaseEditForm},
  User in 'User.pas',
  BaseInfo1 in 'BaseInfo1.pas' {BaseInfo1Form},
  BaseInfoEdit in 'BaseInfoEdit.pas' {BaseInfoEditForm},
  ProductTypeEdit in 'ProductTypeEdit.pas' {ProductTypeEditForm},
  ProductEdit in 'ProductEdit.pas' {ProductEditForm},
  ProductType in 'ProductType.pas' {ProductTypeForm},
  Product in 'Product.pas' {ProductForm},
  BaseMdi in 'BaseMdi.pas' {BaseMdiForm},
  CardSet in 'CardSet.pas' {CardSetForm},
  CardSetEdit in 'CardSetEdit.pas' {CardSetEditForm},
  ProjectEdit in 'ProjectEdit.pas' {ProjectEditForm},
  ProjectTime in 'ProjectTime.pas' {ProjectTimeForm},
  ProjectTimeEdit in 'ProjectTimeEdit.pas' {ProjectTimeEditForm},
  ProjectPrice in 'ProjectPrice.pas' {ProjectPriceForm},
  ProjectPriceEdit in 'ProjectPriceEdit.pas' {ProjectPriceEditForm},
  ProductPrice in 'ProductPrice.pas' {ProductPriceForm},
  ProductPriceEdit in 'ProductPriceEdit.pas' {ProductPriceEditForm},
  MemberManage in 'MemberManage.pas' {MemberManageForm},
  MemberManageEdit in 'MemberManageEdit.pas' {MemberManageEditForm},
  PrepareAgree in 'PrepareAgree.pas' {PrepareAgreeForm},
  PrepareAgreeEdit in 'PrepareAgreeEdit.pas' {PrepareAgreeEditForm},
  Login in 'Login.pas' {LoginForm},
  About in 'About.pas' {AboutForm},
  ProType in 'ProType.pas' {ProTypeForm},
  ProTypeEdit in 'ProTypeEdit.pas' {ProTypeEditForm},
  MemberCardManage in 'MemberCardManage.pas' {MemberCardManageForm},
  SuppleCard in 'SuppleCard.pas' {SuppleCardForm},
  PayOffCard in 'PayOffCard.pas' {PayOffCardForm},
  SumExpense in 'SumExpense.pas' {SumExpenseForm},
  PassMoney in 'PassMoney.pas' {PassMoneyForm},
  BaseMoney in 'BaseMoney.pas' {BaseMoneyForm},
  SaveMoney in 'SaveMoney.pas' {SaveMoneyForm},
  LoseMoney in 'LoseMoney.pas' {LoseMoneyForm},
  PlanOperation in 'PlanOperation.pas' {PlanOperationForm},
  ProPackage in 'ProPackage.pas' {ProPackageForm},
  ProPackageEdit in 'ProPackageEdit.pas' {ProPackageEditForm},
  PrivilegeSet in 'PrivilegeSet.pas' {PrivilegeSetForm},
  ItemEx in 'ItemEx.pas',
  BaseSingleEdit in 'BaseSingleEdit.pas' {BaseSingleEditForm},
  ProductPackage in 'ProductPackage.pas' {ProductPackageForm},
  ProductPackageEdit in 'ProductPackageEdit.pas' {ProductPackageEditForm},
  BaseBill in 'BaseBill.pas' {BaseBillForm},
  Locate in 'Locate.pas' {LocateFrm},
  BaseInfoSelect in 'BaseInfoSelect.pas' {BaseInfoSelectForm},
  BaseProjectSelect in 'BaseProjectSelect.pas' {BaseProjectSelectForm},
  BaseProductSelect in 'BaseProductSelect.pas' {BaseProductSelectForm},
  ProjectProductBill in 'ProjectProductBill.pas' {ProjectProductBillForm},
  ProjectProductBillEdit in 'ProjectProductBillEdit.pas' {ProjectProductBillEditForm},
  ProductSelect in 'ProductSelect.pas' {ProductSelectForm},
  BaseBillEdit in 'BaseBillEdit.pas' {BaseBillEditForm},
  ProjectSelect in 'ProjectSelect.pas' {ProjectSelectForm},
  BaseSearch in 'BaseSearch.pas' {BaseSearchForm},
  MemberManageTotal in 'MemberManageTotal.pas' {MemberManageTotalForm},
  MemberInfo in 'MemberInfo.pas' {MemberInfoForm},
  SaveRpt in 'SaveRpt.pas' {SaveRptForm},
  ColSetup in 'ColSetup.pas' {ColSetupForm},
  BaseDBGridEh in 'BaseDBGridEh.pas' {BaseDBGridEhForm},
  BaseCard in 'BaseCard.pas' {BaseCardForm},
  PrintDBGrid in 'PrintDBGrid.pas',
  MoneyRecord in 'MoneyRecord.pas' {MoneyRecordForm},
  DateForm in 'DateForm.pas',
  OperateLog in 'OperateLog.pas' {OperateLogForm},
  PassEdit1 in 'PassEdit1.pas' {PassEdit1Form},
  SysReset in 'SysReset.pas' {SysResetForm},
  UserLimit1 in 'UserLimit1.pas' {UserLimit1Form},
  Main in 'Main.pas' {MainForm},
  PassEdit in 'PassEdit.pas' {PassEditForm},
  ProjectBill in 'ProjectBill.pas' {ProjectBillForm},
  Project in 'Project.pas' {ProjectForm},
  Unit1 in 'Unit1.pas' {BaseMdiForm1},
  UserEditPass in 'UserEditPass.pas' {UserEditPassForm},
  publicUn in 'publicUn.pas',
  UserInfo in 'UserInfo.pas',
  BaseMdiEdit in 'BaseMdiEdit.pas' {BaseMdiEditForm},
  ShopInfo in 'ShopInfo.pas' {ShopInfoForm},
  ShopInfoEdit in 'ShopInfoEdit.pas' {ShopInfoEditForm},
  ShopDepartEmployeeInfo in 'ShopDepartEmployeeInfo.pas' {ShopDepartEmployeeInfoForm},
  Navigate in 'Navigate.pas' {NavigateForm},
  BaseSdInfo in 'BaseSdInfo.pas' {BaseSdInfoForm},
  Area in 'Area.pas' {AreaForm},
  AreaEdit in 'AreaEdit.pas' {AreaEditForm},
  Depart in 'Depart.pas' {DepartForm},
  DepartEdit in 'DepartEdit.pas' {DepartEditForm},
  Customer in 'Customer.pas' {CustomerForm},
  CustomerEdit in 'CustomerEdit.pas' {CustomerEditForm},
  SoftRegister in 'SoftRegister.pas' {SoftRegisterForm},
  Supplier in 'Supplier.pas' {SupplierForm},
  SupplierEdit in 'SupplierEdit.pas' {SupplierEditForm},
  GoodsType in 'GoodsType.pas' {GoodsTypeForm},
  GoodsTypeEdit in 'GoodsTypeEdit.pas' {GoodsTypeEditForm},
  CalculateUnit in 'CalculateUnit.pas' {CalculateUnitForm},
  CalculateUnitEdit in 'CalculateUnitEdit.pas' {CalculateUnitEditForm},
  Goods in 'Goods.pas' {GoodsForm},
  GoodsEdit in 'GoodsEdit.pas' {GoodsEditForm},
  Warehouse in 'Warehouse.pas' {WarehouseForm},
  WarehouseEdit in 'WarehouseEdit.pas' {WarehouseEditForm},
  Employeetype in 'Employeetype.pas' {EmployeetypeForm},
  EmployeetypeEdit in 'EmployeetypeEdit.pas' {EmployeetypeEditForm},
  Degree in 'Degree.pas' {DegreeForm},
  DegreeEdit in 'DegreeEdit.pas' {DegreeEditForm},
  Employee in 'Employee.pas' {EmployeeForm},
  EmployeeEdit in 'EmployeeEdit.pas' {EmployeeEditForm},
  Billmode in 'Billmode.pas' {BillmodeForm},
  BillmodeEdit in 'BillmodeEdit.pas' {BillmodeEditForm},
  Currencytype in 'Currencytype.pas' {CurrencytypeForm},
  CurrencytypeEdit in 'CurrencytypeEdit.pas' {CurrencytypeEditForm},
  Inouttype in 'Inouttype.pas' {InouttypeForm},
  InouttypeEdit in 'InouttypeEdit.pas' {InouttypeEditForm},
  Cashbank in 'Cashbank.pas' {CashbankForm},
  CashbankEdit in 'CashbankEdit.pas' {CashbankEditForm},
  Compendium in 'Compendium.pas' {CompendiumForm},
  CompendiumEdit in 'CompendiumEdit.pas' {CompendiumEditForm};

{$R *.RES}

begin
  SplashForm := TSplashForm.Create(Application);
  SplashForm.Show;
  SplashForm.Update;

  Application.Initialize;
  Application.Title := '蓝图财务进销存';
  Sleep(3000);
  SplashForm.Hide;
  FreeAndNil(SplashForm);

  Application.CreateForm(TDataMForm, DataMForm);
  Application.CreateForm(TMainForm, MainForm);
  Application.Run;

end.
